### ISSUE TITLE
Not resolving base64 codes

### ISSUE THREAD

**Issue by itsmostafa75** [seramo/merge-subs-worker#2]
سلام جناب.مرسی از کدتون
جناب میشه قابلیت اینکه لینکهای ساب به فرمت base64 رو هم بشه توی کد وارد کرد رو، به کد اضافه کنین؟
ممنون از شما

**Comment by seramo** [comment]
سلام
ممنون از لطفتون
کد فعلی مشکلی با base64 نداره (به عنوان مثال لینک های YeBeKhe که به صورت base64 هستند)

![2023-11-27_15-02](https://github.com/seramo/merge-subs-worker/assets/23317510/1846eb15-a640-4b44-a7b3-c4945320aaff)

در صورتی که مشکل دارید احتمالا این مورد سمت کلاینت (برنامه ای که برای اتصال استفاده می کنید) رخ داده، لطفا این مورد رو مجددا توسط برنامه دیگری بررسی فرمایید

**Comment by itsmostafa75** [comment]
> سلام
> ممنون از لطفتون
> کد فعلی مشکلی با base64 نداره (به عنوان مثال لینک های YeBeKhe که به صورت base64 هستند)
> 
> ![2023-11-27_15-02](https://github.com/seramo/merge-subs-worker/assets/23317510/1846eb15-a640-4b44-a7b3-c4945320aaff)
> 
> در صورتی که مشکل دارید احتمالا این مورد سمت کلاینت (برنامه ای که برای اتصال استفاده می کنید) رخ داده، لطفا این مورد رو مجددا توسط برنامه دیگری بررسی فرمایید

درست می‌فرمایید
مشکل از لینک من بود،مرسی از شما 🌹
