### ISSUE TITLE
issue

### ISSUE THREAD

**Issue by Graveyard9988** [seramo/merge-subs-worker#4]
درود
پس از افزودن ساب های زیر ، لینک ورکر با اررور باز می شود!
      'https://api.nitrosub.site/sub/mikevpn.php',
      'https://api.nitrosub.site/sub/netvpn.php',
      'https://api.nitrosub.site/sub/gofy.php',
      'https://api.nitrosub.site//sub/rosavpn.php',
      'https://api.nitrosub.site//sub/byvpn.php',

**Comment by Graveyard9988** [comment]
لطفا مشکل را برطرف کنید - سپاس

**Comment by seramo** [comment]
سلام
ظاهرا تابع انکد Base64 مشکل داره
بررسی و رفع میشه

**Comment by seramo** [comment]
رفع شد
آخرین نسخه رو بررسی فرمایید

**Comment by Graveyard9988** [comment]
پس از فشردن گزینه deploy با ارور قرمز رنگ زیر مواجه می شوم:
Uncaught SyntaxError: Unexpected string at worker.js:17:8

**Comment by Graveyard9988** [comment]
/**
 * Cloudflare Worker to Merged Subscription URLs
 * Author: SeRaMo ( https://github.com/seramo/ )
 */

addEventListener('fetch', (event) => {
    event.respondWith(handleRequest(event.request));
});

async function handleRequest(request) {
    // Define an array of subscription URLs
    const subscriptionUrls = [
      'https://mrpooya.top/SuperApi/ostrichVIP.php',
      'https://mrpooya.top/SuperApi/confs.php',
      'https://mrpooya.top/SuperApi/V7pRO.php',
      'https://mrpooya.top/SuperApi/ostrich.php'
      'https://api.nitrosub.site/sub/mikevpn.php',
      'https://api.nitrosub.site/sub/netvpn.php',
      'https://api.nitrosub.site/sub/gofy.php',
      'https://api.nitrosub.site//sub/rosavpn.php',
      'https://api.nitrosub.site//sub/byvpn.php',
        // Add more URLs as needed
    ];

    // Define an array of configs
    const staticConfigs = [
        '',
        // Add more configs as needed
    ];

    // Fetch data from all URLs concurrently and store in an array
    const validResponses = await Promise.all(
        subscriptionUrls.map(async (url) => {
            const response = await fetch(url);
            if (response.status === 200) {
                const text = await response.text();
                // Check if the content is a valid base64 encoded string and decode it
                if (isBase64(text)) {
                    const decodedText = atob(text);
                    return decodedText;
                }
                // If not base64, return the text as is
                return text;
            }
            return null; // Ignore failed requests
        })
    );

    // Filter out null values (failed requests)
    const filteredData = validResponses.filter(Boolean);

    // Merge the subscriptions data and static configs
    const mergedData = filteredData.concat(staticConfigs).join('\r\n');

    // Encode the merged data to base64
    const base64Data = encodeBase64(mergedData);

    // Create a response with the merged data
    return new Response(base64Data, {
        status: 200,
    });
}

// Helper function to check if a string is a valid base64 encoded string
function isBase64(str) {
    try {
        return btoa(atob(str)) === str;
    } catch (e) {
        return false;
    }
}

// Encodes a given string into base64 format, handling UTF-8 content correctly.
function encodeBase64(str) {
    const utf8Bytes = new TextEncoder().encode(str);
    let binaryStr = '';
    for (let i = 0; i < utf8Bytes.length; i++) {
        binaryStr += String.fromCharCode(utf8Bytes[i]);
    }
    return btoa(binaryStr);
}

**Comment by seramo** [comment]
خط 16 آخرش رو نبستی
![2024-10-22_09-46](https://github.com/user-attachments/assets/07250843-fbd4-411a-82d4-95cb785fd2c6)

**Comment by Graveyard9988** [comment]
بسته بودم ، اینجا هول هولکی از درفت قبلی کپی شد
الان شما تستش کردی و اوکی بود بزرگوار؟

**Comment by seramo** [comment]
آره درسته
اگه مشکلی داره به جاهایی که قرمز میشه دقت کنه ایراد سینتکسی داری

**Comment by Graveyard9988** [comment]
سپاس بی کران
مشکلی بود مزاحم میشم دوباره.
